spring:
  application:
    name: serviceB
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-interval: 10s
        hostname: ${spring.application.name}
        service-name: ${spring.application.name}
        enabled: true
        instance-id: ${spring.application.name}:${server.port}
        healthCheckUrl: http://localhost:8083/audio2/v1/health
server:
  port: 8083
  servlet:
    context-path: /audio2
logging:
  level:
    com:
      iqiyi: INFO